### ISSUE TITLE
About training settings

### ISSUE THREAD

**Issue by cvbird** [Wenxuan-1119/TransBTS#5]
First of all, thank you for your paper and code. Actually, I am a bit puzzled about the training settings. As mentioned in the paper, the model was trained for 6000 epochs, with batch size 8 on 4 RTX GPU. Indeed I am not quite familiar with this dataset and wonder the scale of it? how many iterations/ steps in each epoch? if the dataset is small, why it takes so many epochs to converge ?
Thanks again!

**Comment by Wenxuan-1119** [comment]
The 3D MRI dataset used in the experiments is provided by the Brain Tumor Segmentation (BraTS) 2019 challenge. It contains 335 cases of patients for training and 125 cases for validation. You can check for more details in our paper. During the experiments, we found that whole network is difficult to converge because of the Transformer part if we only train the network for 500 epochs. So we choose to train the whole network for more epochs at the base of not overfitting.
